# Generated by Django 5.2.5 on 2025-08-28 16:47

import quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='room_code',
            field=models.CharField(default=quiz.models.generate_room_code, max_length=6, unique=True),
        ),
    ]
