# Generated by Django 5.2.5 on 2025-08-29 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_room_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='participants',
            field=models.ManyToManyField(related_name='quiz_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='room_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
